namespace UrbanChallenge.OperationalUI.Graphing {
	partial class formGraph {
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent() {
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(formGraph));
			this.toolStripItems = new System.Windows.Forms.ToolStrip();
			this.plotSurface = new NPlot.Windows.PlotSurface2D();
			this.buttonWindowSize = new System.Windows.Forms.ToolStripDropDownButton();
			this.menuWindow15 = new System.Windows.Forms.ToolStripMenuItem();
			this.menuWindow30 = new System.Windows.Forms.ToolStripMenuItem();
			this.menuWindow1Min = new System.Windows.Forms.ToolStripMenuItem();
			this.menuWindow2Min = new System.Windows.Forms.ToolStripMenuItem();
			this.menuWindow5Min = new System.Windows.Forms.ToolStripMenuItem();
			this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.toolStripItems.SuspendLayout();
			this.SuspendLayout();
			// 
			// toolStripItems
			// 
			this.toolStripItems.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.buttonWindowSize,
            this.toolStripSeparator1});
			this.toolStripItems.Location = new System.Drawing.Point(0, 0);
			this.toolStripItems.Name = "toolStripItems";
			this.toolStripItems.Size = new System.Drawing.Size(513, 25);
			this.toolStripItems.TabIndex = 0;
			this.toolStripItems.Text = "toolStrip1";
			// 
			// plotSurface
			// 
			this.plotSurface.AllowDrop = true;
			this.plotSurface.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.plotSurface.AutoScaleAutoGeneratedAxes = false;
			this.plotSurface.AutoScaleTitle = false;
			this.plotSurface.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.plotSurface.DateTimeToolTip = false;
			this.plotSurface.Legend = null;
			this.plotSurface.LegendZOrder = -1;
			this.plotSurface.Location = new System.Drawing.Point(7, 27);
			this.plotSurface.Name = "plotSurface";
			this.plotSurface.RightMenu = null;
			this.plotSurface.ShowCoordinates = false;
			this.plotSurface.Size = new System.Drawing.Size(499, 218);
			this.plotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.plotSurface.TabIndex = 1;
			this.plotSurface.Text = "plotSurface";
			this.plotSurface.Title = "";
			this.plotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.plotSurface.XAxis1 = null;
			this.plotSurface.XAxis2 = null;
			this.plotSurface.YAxis1 = null;
			this.plotSurface.YAxis2 = null;
			this.plotSurface.DragDrop += new System.Windows.Forms.DragEventHandler(this.plotSurface_DragDrop);
			this.plotSurface.DragEnter += new System.Windows.Forms.DragEventHandler(this.plotSurface_DragEnter);
			// 
			// buttonWindowSize
			// 
			this.buttonWindowSize.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.buttonWindowSize.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.menuWindow15,
            this.menuWindow30,
            this.menuWindow1Min,
            this.menuWindow2Min,
            this.menuWindow5Min});
			this.buttonWindowSize.Image = ((System.Drawing.Image)(resources.GetObject("buttonWindowSize.Image")));
			this.buttonWindowSize.ImageTransparentColor = System.Drawing.Color.Magenta;
			this.buttonWindowSize.Name = "buttonWindowSize";
			this.buttonWindowSize.Size = new System.Drawing.Size(29, 22);
			this.buttonWindowSize.Text = "X-Axis Time Window";
			// 
			// menuWindow15
			// 
			this.menuWindow15.Name = "menuWindow15";
			this.menuWindow15.Size = new System.Drawing.Size(152, 22);
			this.menuWindow15.Tag = "";
			this.menuWindow15.Text = "15 secs";
			this.menuWindow15.Click += new System.EventHandler(this.menuWindow_Click);
			// 
			// menuWindow30
			// 
			this.menuWindow30.Checked = true;
			this.menuWindow30.CheckState = System.Windows.Forms.CheckState.Checked;
			this.menuWindow30.Name = "menuWindow30";
			this.menuWindow30.Size = new System.Drawing.Size(152, 22);
			this.menuWindow30.Tag = "";
			this.menuWindow30.Text = "30 secs";
			this.menuWindow30.Click += new System.EventHandler(this.menuWindow_Click);
			// 
			// menuWindow1Min
			// 
			this.menuWindow1Min.Name = "menuWindow1Min";
			this.menuWindow1Min.Size = new System.Drawing.Size(152, 22);
			this.menuWindow1Min.Tag = "";
			this.menuWindow1Min.Text = "1 min";
			this.menuWindow1Min.Click += new System.EventHandler(this.menuWindow_Click);
			// 
			// menuWindow2Min
			// 
			this.menuWindow2Min.Name = "menuWindow2Min";
			this.menuWindow2Min.Size = new System.Drawing.Size(152, 22);
			this.menuWindow2Min.Tag = "";
			this.menuWindow2Min.Text = "2 min";
			this.menuWindow2Min.Click += new System.EventHandler(this.menuWindow_Click);
			// 
			// menuWindow5Min
			// 
			this.menuWindow5Min.Name = "menuWindow5Min";
			this.menuWindow5Min.Size = new System.Drawing.Size(152, 22);
			this.menuWindow5Min.Tag = "";
			this.menuWindow5Min.Text = "5 min";
			this.menuWindow5Min.Click += new System.EventHandler(this.menuWindow_Click);
			// 
			// toolStripSeparator1
			// 
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			this.toolStripSeparator1.Size = new System.Drawing.Size(6, 25);
			// 
			// formGraph
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(513, 251);
			this.Controls.Add(this.plotSurface);
			this.Controls.Add(this.toolStripItems);
			this.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
			this.Name = "formGraph";
			this.Text = "OperationalUI Graph";
			this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.formGraph_FormClosed);
			this.DragDrop += new System.Windows.Forms.DragEventHandler(this.plotSurface_DragDrop);
			this.DragEnter += new System.Windows.Forms.DragEventHandler(this.plotSurface_DragEnter);
			this.toolStripItems.ResumeLayout(false);
			this.toolStripItems.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.ToolStrip toolStripItems;
		private NPlot.Windows.PlotSurface2D plotSurface;
		private System.Windows.Forms.ToolStripDropDownButton buttonWindowSize;
		private System.Windows.Forms.ToolStripMenuItem menuWindow15;
		private System.Windows.Forms.ToolStripMenuItem menuWindow30;
		private System.Windows.Forms.ToolStripMenuItem menuWindow1Min;
		private System.Windows.Forms.ToolStripMenuItem menuWindow2Min;
		private System.Windows.Forms.ToolStripMenuItem menuWindow5Min;
		private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;

	}
}