//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanChallenge.Arbiter.Core {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ArbiterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ArbiterSettings defaultInstance = ((ArbiterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ArbiterSettings())));
        
        public static ArbiterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SimMode {
            get {
                return ((bool)(this["SimMode"]));
            }
            set {
                this["SimMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintCycleTimesAlways {
            get {
                return ((bool)(this["PrintCycleTimesAlways"]));
            }
            set {
                this["PrintCycleTimesAlways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreVehicles {
            get {
                return ((bool)(this["IgnoreVehicles"]));
            }
            set {
                this["IgnoreVehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTestOperational {
            get {
                return ((bool)(this["UseTestOperational"]));
            }
            set {
                this["UseTestOperational"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldSpoofComputerName {
            get {
                return ((bool)(this["ShouldSpoofComputerName"]));
            }
            set {
                this["ShouldSpoofComputerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SKYNET17")]
        public string SpoofComputerName {
            get {
                return ((string)(this["SpoofComputerName"]));
            }
            set {
                this["SpoofComputerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeBlockageTiming {
            get {
                return ((bool)(this["IncludeBlockageTiming"]));
            }
            set {
                this["IncludeBlockageTiming"] = value;
            }
        }
    }
}
