#ifndef EVENTTYPES_H
#define EVENTTYPES_H

#ifdef __cplusplus_cli
#pragma managed(push,off)
#endif

//A LIST OF DEFINED EVENT TYPES USED BY EVENT QUEUES

//Queue minimum timestamp
#define Q_MINTIMESTAMP 0.0
//Queue maximum timestamp
#define Q_MAXTIMESTAMP 65535.0

//Sensor events
#define BACKCLUSTEREDSICK_EVENT 15
#define BACKJASONROAD_EVENT 401
#define BACKMOBILEYEROAD_EVENT 72
#define BACKMOBILEYEOBSTACLE_EVENT 73
#define BACK0RADAR_EVENT 95
#define DRIV0RADAR_EVENT 99
#define DRIV1RADAR_EVENT 98
#define DRIV2RADAR_EVENT 97
#define DRIV3RADAR_EVENT 96
#define FRONT0RADAR_EVENT 100
#define FRONTJASONROAD_EVENT 400
#define FRONTMOBILEYEROAD_EVENT 70
#define FRONTMOBILEYEOBSTACLE_EVENT 71
#define IBEO_EVENT 80
#define IBEOCENTERRAW_EVENT 81
#define IBEODRIVRAW_EVENT 82
#define IBEOPASSRAW_EVENT 83
#define LOCALMAPTARGETS_EVENT 110
#define LOCALMAPROAD_EVENT 111
#define LOCALMAPPOINTS_EVENT 112
#define ODOM_EVENT 10
#define PASS0RADAR_EVENT 101
#define PASS1RADAR_EVENT 102
#define PASS2RADAR_EVENT 103
#define PASS3RADAR_EVENT 104
#define POSE_EVENT 9
#define SIDESICKDRIV_EVENT 13
#define SIDESICKPASS_EVENT 14
#define STOPLINE_EVENT 50
#define VELODYNE_EVENT 67

//Control events
#define INVALID_EVENT -1
#define QUIT_EVENT -99
#define TRANSMIT_EVENT -2

#ifdef __cplusplus_cli
#pragma managed(pop)
#endif

#endif //EVENTTYPES_H
